### ISSUE TITLE
Multiline spans look weird

### ISSUE THREAD

**Issue by Mateiadrielrafael** [Mesabloo/diagnose#3]
Here's my output:
![image](https://user-images.githubusercontent.com/39400800/165752914-240f783c-c5bc-4ea1-889b-67ce30f25118.png)

1) The middle row does not get highlighted
2) I think the text associated with the multiline span would look better right under it's source, as opposed to the very bottom. It's also weird because there are no dots indicating there's a jump in lines between the first and the second source spans..

Thanks for making this awesome library!

**Comment by Mesabloo** [comment]
Thanks for the report!

The non-connection issue may be caused by a behavior I did actually not think about, where a multiline marker does not end at the last line of the report.
This may be mitigated by your suggestion number 2, which, now that I think about it, is far better than the current design.
I also like your suggestion of putting `⋮` (with an empty line) when multiple ranges of code are not next to each other in the same report.

The issue 1 is however most probably a case I did not handled when coloring source code (when a multiline marker goes over the entire line without beginning/ending on it).
This should be a simple fix, I think. (inline markers need to be prioritized over multiline markers though)

**Comment by Mesabloo** [comment]
@Mateiadrielrafael I managed to reproduce your error completely, with the new enhancements from your suggestions.
This looks like this: 
![image](https://user-images.githubusercontent.com/22964017/166070009-0699f979-126e-4b92-bcaf-9dbd1178070a.png)

All the bugs should have been fixed, and your suggestions have also been implemented : there is now a vertical ellipsis when line numbers are not consecutive -- I am quite unsure if this fits well or not --, and multiline markers are output at the end of the line they stop on.

I think this looks way better now, thanks to your suggestions!

**Comment by Mateiadrielrafael** [comment]
That's super cool! Thanks a lot.

If you don't mind me asking - what color scheme and font do you use? :)

**Comment by Mateiadrielrafael** [comment]
Also, I didn't mean 3 consecutive dots exactly, the more spaced out dots you already used to have are perfectly fine!

**Comment by Mesabloo** [comment]
This indeed looks better with single dots. I didn't quite like the ellipsis (it did not align well, and the ASCII equivalent looked horrible):
![image](https://user-images.githubusercontent.com/22964017/166070962-e8984ff4-c321-4015-b397-2164bf16de82.png)

> If you don't mind me asking - what color scheme and font do you use? :)

I am using the colorscheme [Nord](https://www.nordtheme.com/) (the dark variant) and the font Iosevka Nerd. :slightly_smiling_face: 
I really like Nord and based my whole desktop theme on it!

**Comment by Mesabloo** [comment]
The fixes have been published in the version `1.8.2`.
Thanks again for the report and the cool suggestions!
